### ISSUE TITLE
CTD on Vintage Story version 1.16.0

### ISSUE THREAD

**Issue by OpPointBaker** [AlexDGr8r/temporal-prospector#2]
Version: v1.16.0 (Stable)1/14/2022 1:32:48 AM: Critical error occurred
System.TypeLoadException: Could not load type 'Vintagestory.API.Common.Action`2' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at TemporalProspector.ItemTemporalProspectingPick.ProspectArea(IWorldAccessor world, Entity byEntity, BlockSelection blockSel, Int32 radius, String resourceType)
   at TemporalProspector.ItemTemporalProspectingPick.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at _lb8GGBWOchQLOU3RFFw58Ijkh1D._1NlBQQ8qS5idQptIBQaAbARuOfxA(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
-------------------------------

**Comment by Jacklifear** [comment]
Still exists on 1.17.11

**ERROR LOG:** 
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.11 (Stable)
3/4/2023 10:31:33 AM: Critical error occurred in the following mod: temporalprospector@1.0.0
Loaded Mods: aculinaryartillery@1.0.11, animalcages@2.0.6, Ceramos@0.2.4, chiseltools@1.7.2, furniturelibrary@1.0.7, weaponpackg@1.0.1, hideandfabric@1.2.9, indappledgroves@0.4.7, instruments@1.1.5, aaamakeitcompatible@0.0.2, medieval@1.3.50, moreclasses@1.2.5, rustandrails@1.0.4, superfuel@2.0.7, visibleore@1.0.1, game@1.17.11, wildcrafttrees@1.1.4, wildcraft@1.5.1, alchemy@1.6.7, carryon@0.10.3, expandedfoods@1.6.5, hudclock@2.8.0, medievalexpansion@3.8.1, moreanimals@1.2.3, petai@1.5.5, piingshats@0.2.0, playercorpse@1.5.5, prospectorinfo@4.1.2, stepup@1.2.0, temporalprospector@1.0.0, th3dungeon@0.1.1, creative@1.17.11, survival@1.17.11, VsWaypointSharing@1.0.2, xlib@0.6.14, xrowboat@0.0.5, campaigncartographer@3.1.2, cats@1.5.3, feverstonehorses@1.4.1, feverstonewilds@1.1.0, xinvtweaks@1.4.3, xskills@0.6.14
System.TypeLoadException: Could not load type 'Vintagestory.API.Common.Action`2' from assembly 'VintagestoryAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at TemporalProspector.ItemTemporalProspectingPick.ProspectArea(IWorldAccessor world, Entity byEntity, BlockSelection blockSel, Int32 radius, String resourceType)
   at TemporalProspector.ItemTemporalProspectingPick.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection) in VintagestoryLib\Client\ClientMain.cs:line 2089
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 814
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 600
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1176
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1364
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 204
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 720
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 3/2/2023 6:00:53 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0020001, exception address 00007FF91C78CD29
Stack:
   at System.Environment._Exit(Int32)
   at System.Environment._Exit(Int32)
   at System.Environment.Exit(Int32)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.NativeWindow.OnClosedInternal(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at OpenTK.Platform.Windows.WinGLNative.HandleDestroy(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.Functions.DestroyWindow(IntPtr)
   at OpenTK.Platform.Windows.WinGLNative.DestroyWindow()
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr, OpenTK.Platform.Windows.WindowMessage, IntPtr, IntPtr)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.Functions.DispatchMessage(OpenTK.Platform.Windows.MSG ByRef)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run(Double, Double)
   at Vintagestory.Client.ClientProgram.Start(Vintagestory.Client.ClientProgramArgs, System.String[])
   at Vintagestory.ClientNative.CrashReporter.Start(System.Threading.ThreadStart)
   at Vintagestory.Client.ClientProgram.Main(System.String[])
 }
--------------
{ TimeGenerated = 2/27/2023 10:19:00 AM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2290689270731830376, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 63e108be
P4: StackHash_0000
P5: 0.0.0.0
P6: 00000000
P7: 00000000
P8: PCH_84
P9: 
P10: 

Attached files:
\\?\C:\Users\Jacklifear\AppData\Local\Temp\WER1AAC.tmp.WERDataCollectionStatus.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A4D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A6E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2A7A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2AC9.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_90bdcdd625a86de2a2634c8c2c9cb59115b1c9ff_1112ccc3_3b02837b-f724-4f6b-9b00-56cabd02cc85

Analysis symbol: 
Rechecking for solution: 0
Report Id: 65bb605b-3c23-4a43-a83d-d0940deafb3c
Report Status: 268566528
Hashed bucket: 0614ba6949246beedfca29c150c4f468
Cab Guid: 0 }
--------------
{ TimeGenerated = 2/27/2023 10:18:55 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.17.11.0, time stamp: 0x63e108be
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x00000000
Fault offset: 0x0000000000000000
Faulting process id: 0x4880
Faulting application start time: 0x01d94aafb1da7d8c
Faulting application path: G:\Users\Jacklifear\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: unknown
Report Id: 65bb605b-3c23-4a43-a83d-d0940deafb3c
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Reed10021** [comment]
Fixed with version 1.0.1.
